# Generated by Django 5.0.7 on 2024-08-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatimes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='writter',
            field=models.CharField(max_length=200),
        ),
    ]
